### ISSUE TITLE
Test suite doesn't compile on GHC 8.6

### ISSUE THREAD

**Issue by domenkozar** [GaloisInc/RSA#14]
```
Test.hs:99:8: error:
    • No instance for (Control.Monad.Fail.MonadFail Gen)
        arising from a do statement
        with the failable pattern ‘Right (g :: HashDRBG)’
    • In a stmt of a 'do' block:
        Right (g :: HashDRBG) <- (newGen . BSS.pack)
                                   `fmap` replicateM 4096 arbitrary
      In the expression:
        do Right (g :: HashDRBG) <- (newGen . BSS.pack)
                                      `fmap` replicateM 4096 arbitrary
           case largeRandomPrime g 64 of
             Left _ -> fail "Large prime generation failure."
             Right (i, _) -> return (LP i)
      In an equation for ‘arbitrary’:
          arbitrary
            = do Right (g :: HashDRBG) <- (newGen . BSS.pack)
                                            `fmap` replicateM 4096 arbitrary
                 case largeRandomPrime g 64 of
                   Left _ -> fail "Large prime generation failure."
                   Right (i, _) -> return (LP i)
   |
99 |     do Right (g :: HashDRBG) <- (newGen . BSS.pack) `fmap` replicateM 4096 arbitrary
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by acw** [comment]
Hey, thanks for the heads up. I've fixed the problem, and uploaded the new version as 2.3.1. There's also now an updated Travis file that goes up to 8.6.
