### ISSUE TITLE
Package revisions for GHC 8.8.1

### ISSUE THREAD

**Issue by vmchale** [GaloisInc/RSA#17]
RSA 2.3.1 does not work with GHC 8.8.1, viz.

```
Failed to build RSA-2.3.1.
Build log (
/home/vanessa/.cabal/logs/ghc-8.8.1/RSA-2.3.1-c59e8e4482141f5af242e6d9c4033702e38dc4542988b1a987b598e39b2af471.log
):
Configuring library for RSA-2.3.1..
Preprocessing library for RSA-2.3.1..
Building library for RSA-2.3.1..
[1 of 3] Compiling Codec.Crypto.RSA.Pure ( src/Codec/Crypto/RSA/Pure.hs, dist/build/Codec/Crypto/RSA/Pure.o )

src/Codec/Crypto/RSA/Pure.hs:115:25: error:
    • Could not deduce (MonadFail m) arising from a use of ‘fail’
      from the context: (Monad m, Show a)
        bound by the type signature for:
                   failOnError :: forall (m :: * -> *) a b.
                                  (Monad m, Show a) =>
                                  Either a b -> m b
        at src/Codec/Crypto/RSA/Pure.hs:114:1-53
      Possible fix:
        add (MonadFail m) to the context of
          the type signature for:
            failOnError :: forall (m :: * -> *) a b.
                           (Monad m, Show a) =>
                           Either a b -> m b
    • In the expression: fail (show e)
      In an equation for ‘failOnError’:
          failOnError (Left e) = fail (show e)
    |
115 | failOnError (Left e)  = fail (show e)
    |                         ^^^^^^^^^^^^^
cabal: Failed to build RSA-2.3.1 (which is required by exe:tweet from
tweet-hs-1.0.2.1). See the build log above for details.
```

**Comment by acw** [comment]
@ocharles submitted a pull request to fix this, which I've merged into a feature branch, `ghc-8.8`. I haven't fully merged this into mainline because there are some downstream compatibility problems in `test-framework`.

**Comment by domenkozar** [comment]
Blocking https://github.com/haskell-servant/servant-auth/pull/154

**Comment by mrkkrp** [comment]
Blocking https://github.com/mrkkrp/req/pull/70.

**Comment by mrkkrp** [comment]
Would it be possible to do something about this one? It is preventing a few packages from getting back into Stackage nightly.

**Comment by acw** [comment]
As mentioned in the comment above, I'm moderately uncomfortable merging the branch with so many test suites failing. Granted, they're for unrelated reasons, but it concerns me.

Do you have any suggestions on [how to get the branch to build](https://travis-ci.org/GaloisInc/RSA/branches)?

**Comment by hasufell** [comment]
> As mentioned in the comment above, I'm moderately uncomfortable merging the branch with so many test suites failing

Test suites pass.

```
$ git status
On branch ghc-8.8
$ cabal new-test --enable-tests --allow-newer
Build profile: -w ghc-8.8.1 -O1
In order, the following will be built (use -v for more details):
 - RSA-2.4.1 (test:test-rsa) (ephemeral targets)
Preprocessing test suite 'test-rsa' for RSA-2.4.1..
Building test suite 'test-rsa' for RSA-2.4.1..
Running 1 test suites...
Test suite test-rsa: RUNNING...
Test suite test-rsa: PASS
Test suite logged to:
/home/maerwald/git/RSA/dist-newstyle/build/x86_64-linux/ghc-8.8.1/RSA-2.4.1/t/test-rsa/test/RSA-2.4.1-test-rsa.log
1 of 1 test suites (1 of 1 test cases) passed.
```

**Comment by acw** [comment]
Yes, it passes for GHC >8, but fails for GHC <8 at the moment. I know of at least one user at 7.10.3, who I'd love to continue to support.

**Comment by acw** [comment]
This is now published to Hackage as 2.4.1, and should support 7.8 - 8.8.

**Comment by Bodigrim** [comment]
As a Hackage trustee I made revisions to prohibit unbuildable configurations:
https://hackage.haskell.org/package/RSA-2.3.1/revisions/
https://hackage.haskell.org/package/RSA-2.3.0/revisions/
https://hackage.haskell.org/package/RSA-2.2.0/revisions/
https://hackage.haskell.org/package/RSA-2.1.0.3/revisions/
https://hackage.haskell.org/package/RSA-2.1.0.2/revisions/
https://hackage.haskell.org/package/RSA-2.1.0.1/revisions/
https://hackage.haskell.org/package/RSA-2.1.0/revisions/
